[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["wd_llm_caption*", "wd_llm_caption/configs/*.json"]

[tool.setuptools.dynamic]
version = { file = "VERSION" }

#[tool.setuptools_scm]
#write_to = "wd_llm_caption/version.py"

[tool.ruff]
target-version = "py310"
line-length = 119
indent-width = 4

[tool.ruff.lint]
ignore = ["C408", "C901", "E501", "E731", "E741", "W605"]
select = ["C", "E", "F", "I", "W"]

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["wd_llm_caption"]
known-third-party = [
    "cv2",
    "huggingface_hub",
    "gradio",
    "modelscope",
    "numpy",
    "requests",
    "PIL",
    "tqdm",
    "peft",
    "torch",
    "transformers"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = false
line-ending = "auto"

[project]
name = "wd-llm-caption"
dynamic = ["version"]
authors = [
    { name = "DukeG", email = "fireicewolf@gmail.com" },
]
description = "A Python base cli tool for caption images with WD series, Joy-caption-pre-alpha, meta Llama 3.2 Vision Instruct, Qwen2 VL Instruct, Mini-CPM V2.6 and Florence-2 models."
readme = "README.md"
keywords = ["Image Caption", "WD", "Llama 3.2 Vision Instruct", "Joy Caption Alpha", "Qwen2 VL Instruct", "Mini-CPM V2.6", "Florence-2"]
license = { file = 'LICENSE' }
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "accelerate>=1.5.2",
    "attrdict",
    "bitsandbytes>=0.42.0",
    "einops",
    "gradio>=5.15.0",
    "huggingface_hub>=0.28.1",
    "modelscope>=1.23.2",
    "numpy>=1.26.4,<2.0.0",
    "onnx>=1.17.0",
    "onnxruntime>=1.19.2",
    "opencv-python-headless>=4.11.0.86",
    "openai>=1.61.1",
    "peft>=0.14.0",
    "pillow>=11.1.0",
    "requests>=2.32.3",
    "sentencepiece>=0.2.0",
    "timm>=1.0.15",
    "torch>=2.2.2",
    "tqdm>=4.67.1",
    "transformers>=4.49.0",
]

[project.urls]
Homepage = "https://github.com/fireicewolf/wd-llm-caption-cli"
Issues = "https://github.com/fireicewolf/wd-llm-caption-cli/issues"

[project.scripts]
wd-llm-caption = "wd_llm_caption.caption:main"
wd-llm-caption-gui = "wd_llm_caption.gui:gui"